# Generated by Django 4.2 on 2024-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_direccion_codigopostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=40)),
                ('precio_producto', models.IntegerField(default='not null')),
                ('categoria_producto', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigopostal',
            field=models.IntegerField(default='not null'),
        ),
    ]
