# Generated by Django 4.2 on 2024-12-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productos_alter_direccion_codigopostal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='producto',
        ),
    ]
