# Generated by Django 4.2 on 2024-12-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_producto',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_producto',
            new_name='precio',
        ),
    ]
