# Generated by Django 4.2 on 2025-01-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_categoria_producto_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigopostal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
